-- 360_transport_coverage_lookup.sql
--
-- Data source para el bot "Asistente FYL" de YCloud (Data Connector, HTTPS
-- en vivo): responde "a qué localidad hacen envíos" con la MISMA cobertura
-- por transporte que ya usa la web (client/transportes-data.js). Los datos
-- de esta tabla son copia fiel y completa de las 7 listas fuente:
-- destinos_transporte (SEDE), retiro_del_local, expreso_norte,
-- CREDIFIN_PROVINCIAS (aplanado), viaCargoLocalities (via-cargo-localidades.js),
-- snaiderLocalities (snaider-localidades.js) y mym_cobertura. La función
-- fn_transportes_disponibles replica 1:1 el algoritmo de
-- getTransportesDisponibles(provincia, localidad) de transportes-data.js:
-- override SEDE, excepción Corrientes Capital (solo Retira local + MyM),
-- orden fijo retiro -> expreso -> credifin -> snaider -> via_cargo -> mym,
-- y fallback a Correo Argentino.
--
-- IMPORTANTE: ya existe infraestructura de canonicalización de nombres de
-- transporte para el módulo COD (public.fn_canonicalize_transport_name /
-- public.fn_normalize_transport_key, usadas por resolve_transport_id,
-- fn_closed_order_transport_category, etc., alineadas con
-- scripts/transport-canonical.js). Esta migración NO las duplica: reutiliza
-- esas mismas funciones para canonicalizar los nombres de esta tabla.
-- public.transports es solo el catálogo de 9 entidades transporte (con
-- duplicado histórico "Retira Local"/"Retiro de Local"); no tiene cobertura
-- por localidad, por eso esta tabla nueva no es redundante con esa.
--
-- Esta tabla es una COPIA para consulta del bot, no la fuente de verdad:
-- la fuente de verdad sigue siendo client/transportes-data.js y sus JS de
-- datos. Si esos archivos cambian, esta tabla debe volver a sincronizarse
-- (no hay trigger de sincronización automática todavía).
--
-- Ver docs/FYL-Obsidian/68-CRM-AUTOMATICO-YCLOUD-2026-09-23.md (sección del
-- chatbot Asistente FYL) para el resto del trabajo de revisión del bot.
--
-- Rollback: 360_ROLLBACK_transport_coverage_lookup.sql
-- Tests: 360_transport_coverage_lookup_tests.sql

-- ---------------------------------------------------------------------------
-- 0) Extensión unaccent (mismo patrón que 181_purchase_suppliers_module.sql)
-- ---------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA extensions;

-- ---------------------------------------------------------------------------
-- 1) Tabla: copia plana de las 7 listas fuente
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.transport_coverage (
  id bigserial PRIMARY KEY,
  source text NOT NULL CHECK (source IN ('sede', 'retiro', 'expreso', 'credifin', 'snaider', 'via_cargo', 'mym')),
  provincia text NOT NULL,
  localidad text NOT NULL,
  transporte text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.transport_coverage IS
  '360: copia fiel de las listas de cobertura por transporte de '
  'client/transportes-data.js (y sus data/*.js), para que el bot de YCloud '
  'pueda consultarlas vía Data Connector. No es la fuente de verdad.';

ALTER TABLE public.transport_coverage ENABLE ROW LEVEL SECURITY;
CREATE POLICY transport_coverage_admin_all ON public.transport_coverage
  FOR ALL
  USING (EXISTS (SELECT 1 FROM public.admins a WHERE a.user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.admins a WHERE a.user_id = auth.uid()));

REVOKE ALL ON TABLE public.transport_coverage FROM PUBLIC;
REVOKE ALL ON TABLE public.transport_coverage FROM authenticated;
REVOKE ALL ON TABLE public.transport_coverage FROM anon;

-- ---------------------------------------------------------------------------
-- 2) Normalización de texto
-- ---------------------------------------------------------------------------

-- Mirror de normalize() en transportes-data.js (trim + lower + strip acentos,
-- SIN colapsar espacios internos): se usa para matchear provincia/localidad.
-- Nombre con prefijo fn_transport_coverage_ a propósito, para no competir
-- con public.normalize_transport_name / fn_normalize_transport_key (ya
-- existentes, usados por el módulo COD para nombres de TRANSPORTE, no de
-- provincia/localidad).
CREATE OR REPLACE FUNCTION public.fn_transport_coverage_normalize_locality(p_text text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path TO 'public', 'pg_catalog', 'extensions'
AS $$
  SELECT lower(trim(extensions.unaccent(coalesce(p_text, ''))));
$$;

-- Canonicalización de nombres de transporte: REUTILIZA
-- public.fn_canonicalize_transport_name (ya existente, usada por el módulo
-- COD), no se duplica acá.

CREATE INDEX IF NOT EXISTS idx_transport_coverage_lookup
  ON public.transport_coverage (source, public.fn_transport_coverage_normalize_locality(provincia), public.fn_transport_coverage_normalize_locality(localidad));

-- ---------------------------------------------------------------------------
-- 3) Función principal: mirror 1:1 de getTransportesDisponibles()
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_transportes_disponibles(p_provincia text, p_localidad text)
RETURNS text[]
LANGUAGE plpgsql
STABLE
SET search_path TO 'public', 'pg_catalog', 'extensions'
AS $$
DECLARE
  v_p text := public.fn_transport_coverage_normalize_locality(p_provincia);
  v_l text := public.fn_transport_coverage_normalize_locality(p_localidad);
  v_opciones text[] := '{}';
  v_final text[] := '{}';
  v_raw text;
  v_canonical text;
  v_item text;
BEGIN
  IF v_p = '' OR v_l = '' THEN
    RETURN '{}';
  END IF;

  -- SEDE: si la localidad está en destinos_transporte, solo se envía por SEDE.
  IF EXISTS (
    SELECT 1 FROM public.transport_coverage
    WHERE source = 'sede'
      AND public.fn_transport_coverage_normalize_locality(provincia) = v_p
      AND public.fn_transport_coverage_normalize_locality(localidad) = v_l
  ) THEN
    RETURN ARRAY['SEDE'];
  END IF;

  -- Corrientes Capital: solo Retira local + MyM (excluye Credifin/Snaider/Via Cargo/Correo).
  IF v_p = 'corrientes' AND v_l IN ('corrientes', 'corrientes capital') THEN
    RETURN ARRAY['Retira local', 'MyM'];
  END IF;

  -- Orden fijo: Retiro -> Expreso -> Credifin -> Transporte Snaider -> Via Cargo -> MyM.
  SELECT transporte INTO v_raw FROM public.transport_coverage
    WHERE source = 'retiro' AND public.fn_transport_coverage_normalize_locality(provincia) = v_p AND public.fn_transport_coverage_normalize_locality(localidad) = v_l LIMIT 1;
  IF v_raw IS NOT NULL THEN
    v_opciones := v_opciones || public.fn_canonicalize_transport_name(v_raw)::text;
  END IF;

  SELECT transporte INTO v_raw FROM public.transport_coverage
    WHERE source = 'expreso' AND public.fn_transport_coverage_normalize_locality(provincia) = v_p AND public.fn_transport_coverage_normalize_locality(localidad) = v_l LIMIT 1;
  IF v_raw IS NOT NULL THEN
    v_opciones := v_opciones || public.fn_canonicalize_transport_name(v_raw)::text;
  END IF;

  SELECT transporte INTO v_raw FROM public.transport_coverage
    WHERE source = 'credifin' AND public.fn_transport_coverage_normalize_locality(provincia) = v_p AND public.fn_transport_coverage_normalize_locality(localidad) = v_l LIMIT 1;
  IF v_raw IS NOT NULL THEN
    v_opciones := v_opciones || public.fn_canonicalize_transport_name(v_raw)::text;
  END IF;

  SELECT transporte INTO v_raw FROM public.transport_coverage
    WHERE source = 'snaider' AND public.fn_transport_coverage_normalize_locality(provincia) = v_p AND public.fn_transport_coverage_normalize_locality(localidad) = v_l LIMIT 1;
  IF v_raw IS NOT NULL THEN
    v_canonical := public.fn_canonicalize_transport_name(v_raw);
    IF NOT (v_canonical = ANY(v_opciones)) THEN
      v_opciones := v_opciones || v_canonical::text;
    END IF;
  END IF;

  SELECT transporte INTO v_raw FROM public.transport_coverage
    WHERE source = 'via_cargo' AND public.fn_transport_coverage_normalize_locality(provincia) = v_p AND public.fn_transport_coverage_normalize_locality(localidad) = v_l LIMIT 1;
  IF v_raw IS NOT NULL THEN
    v_canonical := public.fn_canonicalize_transport_name(v_raw);
    IF NOT (v_canonical = ANY(v_opciones)) THEN
      v_opciones := v_opciones || v_canonical::text;
    END IF;
  END IF;

  SELECT transporte INTO v_raw FROM public.transport_coverage
    WHERE source = 'mym' AND public.fn_transport_coverage_normalize_locality(provincia) = v_p AND public.fn_transport_coverage_normalize_locality(localidad) = v_l LIMIT 1;
  IF v_raw IS NOT NULL THEN
    v_canonical := public.fn_canonicalize_transport_name(v_raw);
    IF NOT (v_canonical = ANY(v_opciones)) THEN
      v_opciones := v_opciones || v_canonical::text;
    END IF;
  END IF;

  IF array_length(v_opciones, 1) IS NULL THEN
    v_opciones := ARRAY['Correo Argentino'];
  END IF;

  -- Dedupe preservando orden (canonicalizeTransportList en el JS).
  FOREACH v_item IN ARRAY v_opciones LOOP
    IF NOT (v_item = ANY(v_final)) THEN
      v_final := v_final || v_item::text;
    END IF;
  END LOOP;
  v_opciones := v_final;

  -- Si no hay SEDE en las opciones y no está Correo Argentino, se agrega como alternativa.
  IF NOT ('SEDE' = ANY(v_opciones)) AND array_length(v_opciones, 1) > 0 AND NOT ('Correo Argentino' = ANY(v_opciones)) THEN
    v_opciones := v_opciones || 'Correo Argentino'::text;
  END IF;

  RETURN v_opciones;
END;
$$;

REVOKE ALL ON FUNCTION public.fn_transportes_disponibles(text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_transportes_disponibles(text, text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_transportes_disponibles(text, text) FROM anon;

REVOKE ALL ON FUNCTION public.fn_transport_coverage_normalize_locality(text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_transport_coverage_normalize_locality(text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_transport_coverage_normalize_locality(text) FROM anon;

-- ---------------------------------------------------------------------------
-- 4) Seed: copia fiel de las 7 listas fuente (1005 filas totales)
--    sede=86, retiro=6, expreso=17, credifin=328, via_cargo=475, snaider=92, mym=1
-- ---------------------------------------------------------------------------

DELETE FROM public.transport_coverage;

INSERT INTO public.transport_coverage (source, provincia, localidad, transporte) VALUES
  ('sede', 'Chaco', 'Presidencia Roque Sáenz Peña', 'SEDE'),
  ('sede', 'Chaco', 'Juan José Castelli', 'SEDE'),
  ('sede', 'Chaco', 'Miraflores', 'SEDE'),
  ('sede', 'Chaco', 'Río Bermejo', 'SEDE'),
  ('sede', 'Chaco', 'Hermoso Campo', 'SEDE'),
  ('sede', 'Chaco', 'Quimilí', 'SEDE'),
  ('sede', 'Chaco', 'San Bernardo', 'SEDE'),
  ('sede', 'Chaco', 'La Tigra', 'SEDE'),
  ('sede', 'Chaco', 'La Clotilde', 'SEDE'),
  ('sede', 'Chaco', 'Charata', 'SEDE'),
  ('sede', 'Chaco', 'Villa Ángela', 'SEDE'),
  ('sede', 'Chaco', 'Las Breñas', 'SEDE'),
  ('sede', 'Chaco', 'Corzuela', 'SEDE'),
  ('sede', 'Chaco', 'Campo Largo', 'SEDE'),
  ('sede', 'Chaco', 'Tres Isletas', 'SEDE'),
  ('sede', 'Chaco', 'Gancedo', 'SEDE'),
  ('sede', 'Chaco', 'General San Martín', 'SEDE'),
  ('sede', 'Chaco', 'Pampa del Infierno', 'SEDE'),
  ('sede', 'Chaco', 'Concepción del Bermejo', 'SEDE'),
  ('sede', 'Chaco', 'Los Frentones', 'SEDE'),
  ('sede', 'Chaco', 'Napenay', 'SEDE'),
  ('sede', 'Chaco', 'Avia Terai', 'SEDE'),
  ('sede', 'Chaco', 'Villa Berthet', 'SEDE'),
  ('sede', 'Chaco', 'Santa Sylvina', 'SEDE'),
  ('sede', 'Chaco', 'Coronel Du Graty', 'SEDE'),
  ('sede', 'Chaco', 'Machagai', 'SEDE'),
  ('sede', 'Chaco', 'Quitilipi', 'SEDE'),
  ('sede', 'Chaco', 'Makallé', 'SEDE'),
  ('sede', 'Chaco', 'La Verde', 'SEDE'),
  ('sede', 'Formosa', 'Formosa', 'SEDE'),
  ('sede', 'Formosa', 'General Mansilla', 'SEDE'),
  ('sede', 'Formosa', 'San Martín II', 'SEDE'),
  ('sede', 'Formosa', 'Clorinda', 'SEDE'),
  ('sede', 'Formosa', 'Niclis', 'SEDE'),
  ('sede', 'Formosa', 'Ingeniero Juárez', 'SEDE'),
  ('sede', 'Formosa', 'Pozo del Tigre', 'SEDE'),
  ('sede', 'Formosa', 'Pirané', 'SEDE'),
  ('sede', 'Formosa', 'Las Lomitas', 'SEDE'),
  ('sede', 'Formosa', 'Ibarreta', 'SEDE'),
  ('sede', 'Formosa', 'El Colorado', 'SEDE'),
  ('sede', 'Formosa', 'Palo Santo', 'SEDE'),
  ('sede', 'Formosa', 'Comandante Fontana', 'SEDE'),
  ('sede', 'Corrientes', 'Mercedes', 'SEDE'),
  ('sede', 'Corrientes', 'Mariano I. Loza', 'SEDE'),
  ('sede', 'Corrientes', 'Chavarría', 'SEDE'),
  ('sede', 'Corrientes', 'Felipe Yofre', 'SEDE'),
  ('sede', 'Corrientes', 'Alvear', 'SEDE'),
  ('sede', 'Corrientes', 'La Cruz', 'SEDE'),
  ('sede', 'Corrientes', 'Yapeyú', 'SEDE'),
  ('sede', 'Corrientes', 'San Roque', 'SEDE'),
  ('sede', 'Corrientes', '9 de Julio', 'SEDE'),
  ('sede', 'Corrientes', 'Paso de los Libres', 'SEDE'),
  ('sede', 'Corrientes', 'Curuzú Cuatiá', 'SEDE'),
  ('sede', 'Corrientes', 'Monte Caseros', 'SEDE'),
  ('sede', 'Corrientes', 'Esquina', 'SEDE'),
  ('sede', 'Corrientes', 'Santa Lucía', 'SEDE'),
  ('sede', 'Corrientes', 'Bella Vista', 'SEDE'),
  ('sede', 'Corrientes', 'Saladas', 'SEDE'),
  ('sede', 'Corrientes', 'Goya', 'SEDE'),
  ('sede', 'Corrientes', 'Lavalle', 'SEDE'),
  ('sede', 'Misiones', 'Apóstoles', 'SEDE'),
  ('sede', 'Misiones', 'Oberá', 'SEDE'),
  ('sede', 'Misiones', 'San Vicente', 'SEDE'),
  ('sede', 'Misiones', '2 de Mayo', 'SEDE'),
  ('sede', 'Misiones', 'Aristóbulo del Valle', 'SEDE'),
  ('sede', 'Misiones', 'Leandro N. Alem', 'SEDE'),
  ('sede', 'Misiones', 'Montecarlo', 'SEDE'),
  ('sede', 'Misiones', 'Jardín América', 'SEDE'),
  ('sede', 'Misiones', 'Puerto Rico', 'SEDE'),
  ('sede', 'Misiones', 'Puerto Iguazú', 'SEDE'),
  ('sede', 'Misiones', 'Wanda', 'SEDE'),
  ('sede', 'Misiones', 'Comandante Andresito', 'SEDE'),
  ('sede', 'Misiones', 'Eldorado', 'SEDE'),
  ('sede', 'Misiones', 'San Pedro', 'SEDE'),
  ('sede', 'Misiones', 'Puerto Esperanza', 'SEDE'),
  ('sede', 'Misiones', 'Capioví', 'SEDE'),
  ('sede', 'Misiones', 'San Javier', 'SEDE'),
  ('sede', 'Misiones', 'Candelaria', 'SEDE'),
  ('sede', 'Misiones', 'Bernardo de Irigoyen', 'SEDE'),
  ('sede', 'Misiones', 'El Soberbio', 'SEDE'),
  ('sede', 'Misiones', 'San Ignacio', 'SEDE'),
  ('sede', 'Misiones', 'Santa Ana', 'SEDE'),
  ('sede', 'Misiones', 'Gobernador Roca', 'SEDE'),
  ('sede', 'Misiones', 'San Antonio', 'SEDE'),
  ('sede', 'Misiones', 'Campo Viera', 'SEDE'),
  ('sede', 'Misiones', 'Campo Grande', 'SEDE'),
  ('retiro', 'Chaco', 'Resistencia', 'Retiro de Local'),
  ('retiro', 'Chaco', 'Barranqueras', 'Retiro de Local'),
  ('retiro', 'Chaco', 'Fontana', 'Retiro de Local'),
  ('retiro', 'Chaco', 'Margarita Belén', 'Retiro de Local'),
  ('retiro', 'Chaco', 'Colonia Benítez', 'Retiro de Local'),
  ('retiro', 'Corrientes', 'Corrientes', 'Retiro de Local'),
  ('expreso', 'Corrientes', 'Empedrado', 'Expreso Norte'),
  ('expreso', 'Corrientes', 'San Lorenzo', 'Expreso Norte'),
  ('expreso', 'Corrientes', 'Saladas', 'Expreso Norte'),
  ('expreso', 'Corrientes', 'Bella Vista', 'Expreso Norte'),
  ('expreso', 'Corrientes', 'Santa Lucía', 'Expreso Norte'),
  ('expreso', 'Corrientes', 'Lavalle', 'Expreso Norte'),
  ('expreso', 'Corrientes', 'Monte Caseros', 'Expreso Norte'),
  ('expreso', 'Corrientes', 'Esquina', 'Expreso Norte'),
  ('expreso', 'Corrientes', '9 de Julio', 'Expreso Norte'),
  ('expreso', 'Corrientes', 'San Roque', 'Expreso Norte'),
  ('expreso', 'Corrientes', 'Chavarría', 'Expreso Norte'),
  ('expreso', 'Corrientes', 'Paso de los Libres', 'Expreso Norte'),
  ('expreso', 'Corrientes', 'Mercedes', 'Expreso Norte'),
  ('expreso', 'Corrientes', 'Mariano I. Loza', 'Expreso Norte'),
  ('expreso', 'Corrientes', 'Curuzú Cuatiá', 'Expreso Norte'),
  ('expreso', 'Corrientes', 'Goya', 'Expreso Norte'),
  ('expreso', 'Corrientes', 'Felipe Yofre', 'Expreso Norte'),
  ('credifin', 'Buenos Aires', '11 de Septiembre', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Abasto', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Acassuso', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Adrogue', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Aldo Bonzi', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Alejandro Korn', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Almirante Brown', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Arana', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Arrecifes', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Arturo Segui', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Avellaneda', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Azul', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Bahia Blanca', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Banfield', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Baradero', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Barrio San Jose', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Beccar', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Belen de Escobar', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Bella Vista', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Benavidez', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Berazategui', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Berisso', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Bernal', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Bosques', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Boulogne Sur Mer', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Burzaco', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Cabildo', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Campana', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Canning', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Capital Federal', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Carapachay', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Carlos Keen', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Carlos Spegazzini', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Carmen de Areco', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Caseros', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Castelar', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Chilavert', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Chivilcoy', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Churruca', 'Credifin'),
  ('credifin', 'Buenos Aires', 'City Bell', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Ciudadela', 'Credifin');

INSERT INTO public.transport_coverage (source, provincia, localidad, transporte) VALUES
  ('credifin', 'Buenos Aires', 'Ciudad Jardin', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Claypole', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Cortines', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Crucecita', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Cruce de Florencio Varela', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Del Viso', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Dock Sud', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Don Bosco', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Don Orione', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Don Torcuato', 'Credifin'),
  ('credifin', 'Buenos Aires', 'El Jaguel', 'Credifin'),
  ('credifin', 'Buenos Aires', 'El Libertador', 'Credifin'),
  ('credifin', 'Buenos Aires', 'El Palomar', 'Credifin'),
  ('credifin', 'Buenos Aires', 'El Pato', 'Credifin'),
  ('credifin', 'Buenos Aires', 'El Talar', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Ensenada', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Escobar', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Ezeiza', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Ezpeleta', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Fatima', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Florencio Varela', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Florida Este', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Florida Oeste', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Francisco Alvarez', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Garin', 'Credifin'),
  ('credifin', 'Buenos Aires', 'General Rodriguez', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Gerli', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Gernica', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Glew', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Gonnet', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Gorina', 'Credifin'),
  ('credifin', 'Buenos Aires', 'General Daniel Cerri', 'Credifin'),
  ('credifin', 'Buenos Aires', 'General Pacheco', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Grand Bourg', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Guillermo Hudson', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Gutierrez', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Haedo', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Hurlingham', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Ingeniero Maschwitz', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Ingeniero White', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Isidro Casanova', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Ituzaingo', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Jauregui', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Jose C Paz', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Jose Ingenieros', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Jose Leon Suarez', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Jose Marmol', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Junin', 'Credifin'),
  ('credifin', 'Buenos Aires', 'La Emilia', 'Credifin'),
  ('credifin', 'Buenos Aires', 'La Lonja', 'Credifin'),
  ('credifin', 'Buenos Aires', 'La Lucila', 'Credifin'),
  ('credifin', 'Buenos Aires', 'La Plata', 'Credifin'),
  ('credifin', 'Buenos Aires', 'La Reja', 'Credifin'),
  ('credifin', 'Buenos Aires', 'La Union', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Lanus', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Lavallol', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Lima', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Lisandro Olmos', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Loma Hermosa', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Loma Verde', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Lomas de Zamora', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Lomas del Mirador', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Longchamps', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Los Hornos', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Los Polvorines', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Los Troncos del Talar', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Luis Guillon', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Lujan', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Malaver', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Manuel Alberti', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Manzanares', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Mar del Plata', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Martin Coronado', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Martinez', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Matheu', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Melchor Romero', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Mercedes', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Merlo', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Miguelete', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Ministro Rivadavia', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Monte Chingolo', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Monte Grande', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Moreno', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Moron', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Munro', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Muñiz', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Olavarria', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Olivera', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Olivos', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Open Door', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Pablo Nogues', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Paso del Rey', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Pablo Podesta', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Pereyra', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Pergamino', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Pilar', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Piñeyro', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Platanos', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Presidente Derqui', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Punta Alta', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Punta Lara', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Quilmes', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Remedios de Escalada', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Rafael Calzada', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Ramallo', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Ramos Mejia', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Ranelagh', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Ricardo Rojas', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Rincon de Milberg', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Saenz Peña', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Salto', 'Credifin'),
  ('credifin', 'Buenos Aires', 'San Andres', 'Credifin'),
  ('credifin', 'Buenos Aires', 'San Andres de Giles', 'Credifin'),
  ('credifin', 'Buenos Aires', 'San Antonio de Areco', 'Credifin'),
  ('credifin', 'Buenos Aires', 'San Antonio de Padua', 'Credifin'),
  ('credifin', 'Buenos Aires', 'San Fernando', 'Credifin'),
  ('credifin', 'Buenos Aires', 'San Francisco Solano', 'Credifin'),
  ('credifin', 'Buenos Aires', 'San Isidro', 'Credifin'),
  ('credifin', 'Buenos Aires', 'San Justo', 'Credifin'),
  ('credifin', 'Buenos Aires', 'San Martin', 'Credifin'),
  ('credifin', 'Buenos Aires', 'San Miguel', 'Credifin'),
  ('credifin', 'Buenos Aires', 'San Nicolas', 'Credifin'),
  ('credifin', 'Buenos Aires', 'San Pedro', 'Credifin'),
  ('credifin', 'Buenos Aires', 'San Vicente', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Santos Lugares', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Sarandi', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Sourigues', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Tablada', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Tandil', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Tapiales', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Temperley', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Tigre', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Tolosa', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Tortuguitas', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Tres Arroyos', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Tristan Suarez', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Turdera', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Valentin Alsina', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Vicente Lopez', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Victoria', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Villa Adelina', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Villa Ballester', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Villa Bosch', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Villa Celina', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Villa Dominico', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Villa Elisa', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Villa España', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Villa Insuperable', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Villa La Florida', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Villa Luzuriaga', 'Credifin');

INSERT INTO public.transport_coverage (source, provincia, localidad, transporte) VALUES
  ('credifin', 'Buenos Aires', 'Villa Lynch', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Villa Madero', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Villa Maipu', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Villa Martelli', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Villa Raffo', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Villa Ramallo', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Villa Rosa', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Villa Santos Tesei', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Villa Sarmiento', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Virreyes', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Wilde', 'Credifin'),
  ('credifin', 'Buenos Aires', 'Zarate', 'Credifin'),
  ('credifin', 'Chaco', 'Barranqueras', 'Credifin'),
  ('credifin', 'Chaco', 'Charata', 'Credifin'),
  ('credifin', 'Chaco', 'Colonias Unidas', 'Credifin'),
  ('credifin', 'Chaco', 'Coronel Du Graty', 'Credifin'),
  ('credifin', 'Chaco', 'Corzuela', 'Credifin'),
  ('credifin', 'Chaco', 'Fontana', 'Credifin'),
  ('credifin', 'Chaco', 'General Jose de San Martin', 'Credifin'),
  ('credifin', 'Chaco', 'General Pinedo', 'Credifin'),
  ('credifin', 'Chaco', 'Hermoso Campo', 'Credifin'),
  ('credifin', 'Chaco', 'Las Breñas', 'Credifin'),
  ('credifin', 'Chaco', 'Machagai', 'Credifin'),
  ('credifin', 'Chaco', 'Presidencia Roque Saenz Peña', 'Credifin'),
  ('credifin', 'Chaco', 'Puerto Tirol', 'Credifin'),
  ('credifin', 'Chaco', 'Puerto Vilelas', 'Credifin'),
  ('credifin', 'Chaco', 'Quitilipi', 'Credifin'),
  ('credifin', 'Chaco', 'Resistencia', 'Credifin'),
  ('credifin', 'Chaco', 'Santa Sylvina', 'Credifin'),
  ('credifin', 'Chaco', 'Villa Angela', 'Credifin'),
  ('credifin', 'Chaco', 'Gancedo', 'Credifin'),
  ('credifin', 'Corrientes', 'Corrientes', 'Credifin'),
  ('credifin', 'Corrientes', 'Colonia Carolina', 'Credifin'),
  ('credifin', 'Corrientes', 'Goya', 'Credifin'),
  ('credifin', 'Corrientes', 'Lavalle', 'Credifin'),
  ('credifin', 'Corrientes', 'Santa Lucia', 'Credifin'),
  ('credifin', 'Corrientes', 'Paso de los Libres', 'Credifin'),
  ('credifin', 'Formosa', 'Formosa', 'Credifin'),
  ('credifin', 'Formosa', 'Clorinda', 'Credifin'),
  ('credifin', 'Formosa', 'El Colorado', 'Credifin'),
  ('credifin', 'Formosa', 'Ibarreta', 'Credifin'),
  ('credifin', 'Formosa', 'Laguna Naineck', 'Credifin'),
  ('credifin', 'Formosa', 'Laguna Blanca', 'Credifin'),
  ('credifin', 'Formosa', 'Espinillo', 'Credifin'),
  ('credifin', 'Formosa', 'General Belgrano', 'Credifin'),
  ('credifin', 'Formosa', 'Pirane', 'Credifin'),
  ('credifin', 'Formosa', 'Villa 213', 'Credifin'),
  ('credifin', 'Entre Ríos', 'Colon', 'Credifin'),
  ('credifin', 'Entre Ríos', 'Concepcion del Uruguay', 'Credifin'),
  ('credifin', 'Entre Ríos', 'Concordia', 'Credifin'),
  ('credifin', 'Entre Ríos', 'Crespo', 'Credifin'),
  ('credifin', 'Entre Ríos', 'Diamante', 'Credifin'),
  ('credifin', 'Entre Ríos', 'General Ramirez', 'Credifin'),
  ('credifin', 'Entre Ríos', 'Gualeguaychu', 'Credifin'),
  ('credifin', 'Entre Ríos', 'Parana', 'Credifin'),
  ('credifin', 'Entre Ríos', 'San Jose', 'Credifin'),
  ('credifin', 'Entre Ríos', 'Villa Elisa', 'Credifin'),
  ('credifin', 'Córdoba', 'Alta Gracia', 'Credifin'),
  ('credifin', 'Córdoba', 'Arroyito', 'Credifin'),
  ('credifin', 'Córdoba', 'Bell Ville', 'Credifin'),
  ('credifin', 'Córdoba', 'Cordoba', 'Credifin'),
  ('credifin', 'Córdoba', 'General Deheza', 'Credifin'),
  ('credifin', 'Córdoba', 'Jesus Maria', 'Credifin'),
  ('credifin', 'Córdoba', 'La Carlota', 'Credifin'),
  ('credifin', 'Córdoba', 'La Falda', 'Credifin'),
  ('credifin', 'Córdoba', 'Las Varillas', 'Credifin'),
  ('credifin', 'Córdoba', 'Marcos Juarez', 'Credifin'),
  ('credifin', 'Córdoba', 'Monte Cristo', 'Credifin'),
  ('credifin', 'Córdoba', 'Morteros', 'Credifin'),
  ('credifin', 'Córdoba', 'Oncativo', 'Credifin'),
  ('credifin', 'Córdoba', 'Rio Cuarto', 'Credifin'),
  ('credifin', 'Córdoba', 'Rio Primero', 'Credifin'),
  ('credifin', 'Córdoba', 'Rio Segundo', 'Credifin'),
  ('credifin', 'Córdoba', 'Rio Tercero', 'Credifin'),
  ('credifin', 'Córdoba', 'San Francisco', 'Credifin'),
  ('credifin', 'Córdoba', 'Villa Allende', 'Credifin'),
  ('credifin', 'Córdoba', 'Villa Carlos Paz', 'Credifin'),
  ('credifin', 'Córdoba', 'Villa General Belgrano', 'Credifin'),
  ('credifin', 'Córdoba', 'Villa Maria', 'Credifin'),
  ('credifin', 'Santa Fe', 'Avellaneda', 'Credifin'),
  ('credifin', 'Santa Fe', 'Calchaqui', 'Credifin'),
  ('credifin', 'Santa Fe', 'Cañada de Gomez', 'Credifin'),
  ('credifin', 'Santa Fe', 'Casilda', 'Credifin'),
  ('credifin', 'Santa Fe', 'Ceres', 'Credifin'),
  ('credifin', 'Santa Fe', 'Chabas', 'Credifin'),
  ('credifin', 'Santa Fe', 'El Trebol', 'Credifin'),
  ('credifin', 'Santa Fe', 'Esperanza', 'Credifin'),
  ('credifin', 'Santa Fe', 'Firmat', 'Credifin'),
  ('credifin', 'Santa Fe', 'Franck', 'Credifin'),
  ('credifin', 'Santa Fe', 'Granadero Baigorria', 'Credifin'),
  ('credifin', 'Santa Fe', 'Las Toscas', 'Credifin'),
  ('credifin', 'Santa Fe', 'Rafaela', 'Credifin'),
  ('credifin', 'Santa Fe', 'Reconquista', 'Credifin'),
  ('credifin', 'Santa Fe', 'Rosario', 'Credifin'),
  ('credifin', 'Santa Fe', 'San Jorge', 'Credifin'),
  ('credifin', 'Santa Fe', 'San Justo', 'Credifin'),
  ('credifin', 'Santa Fe', 'San Lorenzo', 'Credifin'),
  ('credifin', 'Santa Fe', 'Santa Fe', 'Credifin'),
  ('credifin', 'Santa Fe', 'Santo Tome', 'Credifin'),
  ('credifin', 'Santa Fe', 'Sunchales', 'Credifin'),
  ('credifin', 'Santa Fe', 'Tostado', 'Credifin'),
  ('credifin', 'Santa Fe', 'Venado Tuerto', 'Credifin'),
  ('credifin', 'Santa Fe', 'Vera', 'Credifin'),
  ('credifin', 'Santa Fe', 'Villa Constitucion', 'Credifin'),
  ('credifin', 'Santa Fe', 'Villa Gobernador Galvez', 'Credifin'),
  ('credifin', 'Santiago del Estero', 'Bandera', 'Credifin'),
  ('credifin', 'Santiago del Estero', 'Juries', 'Credifin'),
  ('credifin', 'Santiago del Estero', 'La Banda', 'Credifin'),
  ('credifin', 'Santiago del Estero', 'Quimili', 'Credifin'),
  ('credifin', 'Santiago del Estero', 'Santiago del Estero', 'Credifin'),
  ('credifin', 'Tucumán', 'Alderetes', 'Credifin'),
  ('credifin', 'Tucumán', 'Banda del Rio Sali', 'Credifin'),
  ('credifin', 'Tucumán', 'Cevil Redondo', 'Credifin'),
  ('credifin', 'Tucumán', 'El Manantial', 'Credifin'),
  ('credifin', 'Tucumán', 'Las Talitas', 'Credifin'),
  ('credifin', 'Tucumán', 'Lastenia', 'Credifin'),
  ('credifin', 'Tucumán', 'Los Pocitos', 'Credifin'),
  ('credifin', 'Tucumán', 'San Andres', 'Credifin'),
  ('credifin', 'Tucumán', 'San Pablo', 'Credifin'),
  ('credifin', 'Tucumán', 'Tafi Viejo', 'Credifin'),
  ('credifin', 'Tucumán', 'Villa Carmela', 'Credifin'),
  ('credifin', 'Tucumán', 'Yerba Buena', 'Credifin'),
  ('credifin', 'Tucumán', 'San Miguel de Tucuman', 'Credifin'),
  ('credifin', 'Misiones', 'Posadas', 'Credifin'),
  ('credifin', 'Mendoza', 'Godoy Cruz', 'Credifin'),
  ('credifin', 'Mendoza', 'Guaymallen', 'Credifin'),
  ('credifin', 'Mendoza', 'Las Heras', 'Credifin'),
  ('credifin', 'Mendoza', 'Lujan de Cuyo', 'Credifin'),
  ('credifin', 'Mendoza', 'Maipu', 'Credifin'),
  ('credifin', 'Mendoza', 'Palmira', 'Credifin'),
  ('credifin', 'Mendoza', 'San Rafael', 'Credifin'),
  ('credifin', 'Mendoza', 'Tunuyan', 'Credifin'),
  ('credifin', 'San Juan', 'San Juan', 'Credifin'),
  ('credifin', 'San Juan', 'Pocito', 'Credifin'),
  ('credifin', 'San Juan', 'Santa Lucia', 'Credifin'),
  ('credifin', 'San Luis', 'San Luis', 'Credifin'),
  ('credifin', 'La Rioja', 'La Rioja', 'Credifin'),
  ('via_cargo', 'Buenos Aires', '9 de Abril', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', '9 de Julio', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'alejandro korn', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Avellaneda', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Ayacucho', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Azul', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Bahia Blanca', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Balcarce', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Baradero', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Bella Vista', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Benavidez', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Benito Juarez', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Berazategui', 'Via Cargo');

INSERT INTO public.transport_coverage (source, provincia, localidad, transporte) VALUES
  ('via_cargo', 'Buenos Aires', 'Bernal', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Bolivar', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Boulogne', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Bragado', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Burzaco', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Campana', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Canning', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Cañuelas', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Carhue (BA)', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Carlos Casares', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Caseros', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Castelar', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Chacabuco', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Chivilcoy', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Ciudadela', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Claromeco', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Colon (BUE)', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Coronel Dorrego', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Coronel Pringles', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'CORONEL SUAREZ(BUE)', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Del Viso', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Dolores', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Don Torcuato', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'El Palomar', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Escobar', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Ezeiza', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Florencio Varela', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Florida', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Garin', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'General Pacheco', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'General Rodriguez', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'General Villegas', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Gonzalez Catan', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Gregorio de Laferrere', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Guernica', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Haedo', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Hudson(BUE)', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Hurlingham', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Ingeniero Maschwitz', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Isidro Casanova', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Ituzaingo (BUE)', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Jose Clemente Paz', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Junin', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'La Lucila', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'La Plata', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'La Tablada', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Lanus', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Las Flores', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Las Toninas', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Lavallol', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Lincoln', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Lobos', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Loma Hermosa', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Lomas de Zamora', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Lomas de Zamora Centro', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Lomas del Mirador', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Longchamps', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Los Hornos', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Lujan', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Maipu', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Mar de Ajo', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Mar del Plata', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Mar del Tuyú', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Marcos Paz', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Martinez', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Mataderos', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Matheu', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Mercedes', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Merlo', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Miramar', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Monte Grande', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Moreno', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Moron', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Munro', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Muñiz', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Necochea', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Olavarria', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Olivos', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Parque Leloir', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Parque San Martin (Merlo)', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Paso del Rey', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Pehuajo', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Pergamino', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Pilar', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Pinamar', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Pinamar Terminal', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Puente La Noria', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Punta Alta', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Quilmes', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Rafael Calzada', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Rafael Castillo', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Ramallo', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Ramos Mejia', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Rauch', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Rojas', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Roque Perez', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'SALADILLO (BUE)', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Salto', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'San Andrés de Giles (BA)', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'San Antonio de Areco', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'San Antonio de Padua', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'San Bernardo', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'San Clemente del Tuyu', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'San Fernando', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'San Francisco Solano', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'San Isidro', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'San Justo', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'San Martin', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'San Miguel', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'San Miguel del Monte', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'San Nicolas de los Arroyos', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'San Pedro (Bue)', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Santa Clara del Mar', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Santa Teresita', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Sarandi', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Tandil', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Temperley', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Tigre', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Tolosa', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Tortuguitas', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Trenque Lauquen', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Tres Arroyos', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Tristan Suarez', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Turdera', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Villa Ballester', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Villa Bosch', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Villa Celina', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Villa Gesell', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Villa Luzuriaga', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Villa Lynch', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Villa Madero', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Villa Martelli', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Villa Sarmiento', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Villa Tesei', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Virrey del Pino', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Virreyes', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Wilde', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'William Morris', 'Via Cargo'),
  ('via_cargo', 'Buenos Aires', 'Zarate', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Agronomia', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Almagro', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Balvanera', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Barracas', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Barrio Norte', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Belgrano', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Boedo', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Caballito', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Chacarita', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Cohglan', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Colegiales', 'Via Cargo');

INSERT INTO public.transport_coverage (source, provincia, localidad, transporte) VALUES
  ('via_cargo', 'CABA', 'Constitucion', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Flores', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Floresta', 'Via Cargo'),
  ('via_cargo', 'CABA', 'La Boca', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Liniers', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Mataderos', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Microcentro', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Monserrat', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Monte Castro', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Nueva Pompeya', 'Via Cargo'),
  ('via_cargo', 'CABA', 'ONCE', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Palermo', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Parque Avellaneda', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Parque Chacabuco', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Parque Patricios', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Paternal', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Puente Saavedra', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Retiro', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Tribunales', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Velez Sarsfield', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Villa Crespo', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Villa del Parque', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Villa Devoto', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Villa Lugano', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Villa Luro', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Villa Ortuzar', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Villa Pueyrredon', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Villa Soldati', 'Via Cargo'),
  ('via_cargo', 'CABA', 'Villa Urquiza', 'Via Cargo'),
  ('via_cargo', 'Catamarca', 'Catamarca', 'Via Cargo'),
  ('via_cargo', 'Catamarca', 'Recreo', 'Via Cargo'),
  ('via_cargo', 'Chaco', 'Avia Terai', 'Via Cargo'),
  ('via_cargo', 'Chaco', 'Campo Largo', 'Via Cargo'),
  ('via_cargo', 'Chaco', 'Castelli', 'Via Cargo'),
  ('via_cargo', 'Chaco', 'Charata', 'Via Cargo'),
  ('via_cargo', 'Chaco', 'Coronel Du Graty', 'Via Cargo'),
  ('via_cargo', 'Chaco', 'General Jose de San Martin', 'Via Cargo'),
  ('via_cargo', 'Chaco', 'General Pinedo', 'Via Cargo'),
  ('via_cargo', 'Chaco', 'Hermoso Campo', 'Via Cargo'),
  ('via_cargo', 'Chaco', 'Las Breñas', 'Via Cargo'),
  ('via_cargo', 'Chaco', 'Machagai', 'Via Cargo'),
  ('via_cargo', 'Chaco', 'Presidencia de la Plaza', 'Via Cargo'),
  ('via_cargo', 'Chaco', 'Quitilipi', 'Via Cargo'),
  ('via_cargo', 'Chaco', 'Resistencia', 'Via Cargo'),
  ('via_cargo', 'Chaco', 'Roque Saenz Peña', 'Via Cargo'),
  ('via_cargo', 'Chaco', 'Santa Sylvina', 'Via Cargo'),
  ('via_cargo', 'Chaco', 'Taco Pozo CHC', 'Via Cargo'),
  ('via_cargo', 'Chaco', 'Villa Angela (CHC)', 'Via Cargo'),
  ('via_cargo', 'Chubut', 'Comodoro Rivadavia', 'Via Cargo'),
  ('via_cargo', 'Chubut', 'El Hoyo', 'Via Cargo'),
  ('via_cargo', 'Chubut', 'El Maiten', 'Via Cargo'),
  ('via_cargo', 'Chubut', 'Epuyen', 'Via Cargo'),
  ('via_cargo', 'Chubut', 'Esquel', 'Via Cargo'),
  ('via_cargo', 'Chubut', 'Gaiman', 'Via Cargo'),
  ('via_cargo', 'Chubut', 'Lago Puelo', 'Via Cargo'),
  ('via_cargo', 'Chubut', 'Puerto Madryn', 'Via Cargo'),
  ('via_cargo', 'Chubut', 'Rada Tilly', 'Via Cargo'),
  ('via_cargo', 'Chubut', 'Rawson', 'Via Cargo'),
  ('via_cargo', 'Chubut', 'Sarmiento', 'Via Cargo'),
  ('via_cargo', 'Chubut', 'Trelew', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Almafuerte', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Alta Gracia', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Arias', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Arroyito (CBA)', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Bell Ville', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Berrotaran', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Capilla del Monte', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Colonia Caroya', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Cordoba', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Corral de Bustos', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Cosquin', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Cruz del Eje', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Dean Funes', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Despeñaderos', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Embalse', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'General Deheza', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Jesus Maria', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'La Calera', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'La Carlota', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'La Falda', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Laboulaye', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Las Varillas', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Leones', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Malvinas Argentinas', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Marcos Juarez', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Monte Maiz', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Morteros (CBA)', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Rio Ceballos', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Rio Cuarto', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Rio Primero', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Rio Segundo', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Rio Tercero', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Sampacho (CB)', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'San Francisco', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'San Jose de la Dormida', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Santa Rosa de Calamuchita', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Serrezuela', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Vicuña Mackenna', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Villa Allende', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Villa Carlos Paz', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Villa Cura Brochero', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Villa de Las Rosas', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Villa de Soto', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Villa del Rosario', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Villa del Totoral', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Villa Dolores', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Villa General Belgrano', 'Via Cargo'),
  ('via_cargo', 'Córdoba', 'Villa Maria', 'Via Cargo'),
  ('via_cargo', 'Corrientes', 'Alvear', 'Via Cargo'),
  ('via_cargo', 'Corrientes', 'Bella Vista (CRT)', 'Via Cargo'),
  ('via_cargo', 'Corrientes', 'CORRIENTES', 'Via Cargo'),
  ('via_cargo', 'Corrientes', 'Curuzu Cuatia', 'Via Cargo'),
  ('via_cargo', 'Corrientes', 'Empedrado', 'Via Cargo'),
  ('via_cargo', 'Corrientes', 'Esquina', 'Via Cargo'),
  ('via_cargo', 'Corrientes', 'Goya (CRT)', 'Via Cargo'),
  ('via_cargo', 'Corrientes', 'Itati', 'Via Cargo'),
  ('via_cargo', 'Corrientes', 'Ituzaingo', 'Via Cargo'),
  ('via_cargo', 'Corrientes', 'La Cruz', 'Via Cargo'),
  ('via_cargo', 'Corrientes', 'Mercedes', 'Via Cargo'),
  ('via_cargo', 'Corrientes', 'Monte Caseros', 'Via Cargo'),
  ('via_cargo', 'Corrientes', 'Paso de Los Libres', 'Via Cargo'),
  ('via_cargo', 'Corrientes', 'Saladas(CRT)', 'Via Cargo'),
  ('via_cargo', 'Corrientes', 'Santa Lucia(CRT)', 'Via Cargo'),
  ('via_cargo', 'Corrientes', 'Santo Tome', 'Via Cargo'),
  ('via_cargo', 'Corrientes', 'Virasoro', 'Via Cargo'),
  ('via_cargo', 'Entre Ríos', 'Basavilbaso', 'Via Cargo'),
  ('via_cargo', 'Entre Ríos', 'Chajari', 'Via Cargo'),
  ('via_cargo', 'Entre Ríos', 'Colon (ENT)', 'Via Cargo'),
  ('via_cargo', 'Entre Ríos', 'Concepcion del Uruguay', 'Via Cargo'),
  ('via_cargo', 'Entre Ríos', 'Concordia', 'Via Cargo'),
  ('via_cargo', 'Entre Ríos', 'Crespo', 'Via Cargo'),
  ('via_cargo', 'Entre Ríos', 'Diamante', 'Via Cargo'),
  ('via_cargo', 'Entre Ríos', 'Federacion', 'Via Cargo'),
  ('via_cargo', 'Entre Ríos', 'Gualeguay', 'Via Cargo'),
  ('via_cargo', 'Entre Ríos', 'Gualeguaychu', 'Via Cargo'),
  ('via_cargo', 'Entre Ríos', 'La Paz', 'Via Cargo'),
  ('via_cargo', 'Entre Ríos', 'Nogoya', 'Via Cargo'),
  ('via_cargo', 'Entre Ríos', 'Parana', 'Via Cargo'),
  ('via_cargo', 'Entre Ríos', 'San José (ER)', 'Via Cargo'),
  ('via_cargo', 'Entre Ríos', 'Victoria', 'Via Cargo'),
  ('via_cargo', 'Entre Ríos', 'Villaguay', 'Via Cargo'),
  ('via_cargo', 'Formosa', 'Clorinda', 'Via Cargo'),
  ('via_cargo', 'Formosa', 'El Colorado', 'Via Cargo'),
  ('via_cargo', 'Formosa', 'Formosa', 'Via Cargo'),
  ('via_cargo', 'Formosa', 'Pirane', 'Via Cargo'),
  ('via_cargo', 'Jujuy', 'Humahuaca', 'Via Cargo'),
  ('via_cargo', 'Jujuy', 'La Quiaca', 'Via Cargo'),
  ('via_cargo', 'Jujuy', 'Libertador General San Martin', 'Via Cargo'),
  ('via_cargo', 'Jujuy', 'Palpala', 'Via Cargo'),
  ('via_cargo', 'Jujuy', 'Perico', 'Via Cargo');

INSERT INTO public.transport_coverage (source, provincia, localidad, transporte) VALUES
  ('via_cargo', 'Jujuy', 'Purmamarca', 'Via Cargo'),
  ('via_cargo', 'Jujuy', 'San Pedro de Jujuy', 'Via Cargo'),
  ('via_cargo', 'Jujuy', 'San Salvador de Jujuy', 'Via Cargo'),
  ('via_cargo', 'Jujuy', 'Tilcara', 'Via Cargo'),
  ('via_cargo', 'La Pampa', '25 de Mayo', 'Via Cargo'),
  ('via_cargo', 'La Pampa', 'General Acha', 'Via Cargo'),
  ('via_cargo', 'La Pampa', 'General Pico', 'Via Cargo'),
  ('via_cargo', 'La Pampa', 'Macachin', 'Via Cargo'),
  ('via_cargo', 'La Pampa', 'Realico', 'Via Cargo'),
  ('via_cargo', 'La Pampa', 'Santa Isabel', 'Via Cargo'),
  ('via_cargo', 'La Pampa', 'SANTA ROSA', 'Via Cargo'),
  ('via_cargo', 'La Rioja', 'Chilecito', 'Via Cargo'),
  ('via_cargo', 'La Rioja', 'La Rioja', 'Via Cargo'),
  ('via_cargo', 'Mendoza', 'General Alvear', 'Via Cargo'),
  ('via_cargo', 'Mendoza', 'General Alvear (MDZ)', 'Via Cargo'),
  ('via_cargo', 'Mendoza', 'Libertador Gral San Martin', 'Via Cargo'),
  ('via_cargo', 'Mendoza', 'Malargue', 'Via Cargo'),
  ('via_cargo', 'Mendoza', 'Mendoza', 'Via Cargo'),
  ('via_cargo', 'Mendoza', 'San Carlos', 'Via Cargo'),
  ('via_cargo', 'Mendoza', 'San Rafael', 'Via Cargo'),
  ('via_cargo', 'Mendoza', 'Tunuyan', 'Via Cargo'),
  ('via_cargo', 'Mendoza', 'Tupungato', 'Via Cargo'),
  ('via_cargo', 'Mendoza', 'Villa Atuel', 'Via Cargo'),
  ('via_cargo', 'Misiones', '2 de Mayo', 'Via Cargo'),
  ('via_cargo', 'Misiones', '9 de Julio', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Apostoles', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Aristobulo del Valle', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Bernardo de Irigoyen', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Campo Grande', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Candelaria', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Capiovi', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Colonia Delicia', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Comandante Andresito', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'El Soberbio', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Eldorado', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Garuhape', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Garupa', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Gobernador Roca', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Jardin America', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Leandro N Alem', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Montecarlo', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Obera', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Posadas', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Puerto Esperanza', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Puerto Iguazu', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Puerto Piray', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Puerto Rico', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'San Antonio (MIS)', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'San Ignacio', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'San Javier', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'San Jose (MIS)', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'San Pedro', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'San Vicente', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Santa Ana', 'Via Cargo'),
  ('via_cargo', 'Misiones', 'Wanda', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'Alumine', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'Andacollo', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'Añelo', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'Barrancas', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'Buta Ranquil', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'Centenario', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'Chos Malal', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'Cutral Co', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'Junin de los Andes', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'Las Ovejas', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'NEUQUEN', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'Picun Leufu', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'Piedra del Aguila', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'Plottier', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'Rincon de los Sauces', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'San Martin de los Andes', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'San Patricio del Chañar', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'Senillosa', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'Villa La Angostura', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'Villa Pehuenia', 'Via Cargo'),
  ('via_cargo', 'Neuquén', 'Zapala', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'Allen', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'Bariloche', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'Chimpay', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'Choele Choel', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'Cinco Saltos', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'Cipolletti', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'Colonia Catriel', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'Dina Huapi', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'El Bolson', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'Fernandez Oro', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'General Conesa', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'General Roca', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'Ingeniero Huergo', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'Lamarque', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'Las Grutas', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'Luis Beltran', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'Rio Colorado', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'San Antonio Oeste', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'Sierra Grande', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'Viedma', 'Via Cargo'),
  ('via_cargo', 'Río Negro', 'Villa Regina', 'Via Cargo'),
  ('via_cargo', 'Salta', 'Aguaray', 'Via Cargo'),
  ('via_cargo', 'Salta', 'General Guemes', 'Via Cargo'),
  ('via_cargo', 'Salta', 'General Mosconi', 'Via Cargo'),
  ('via_cargo', 'Salta', 'Metan', 'Via Cargo'),
  ('via_cargo', 'Salta', 'Oran', 'Via Cargo'),
  ('via_cargo', 'Salta', 'Pichanal', 'Via Cargo'),
  ('via_cargo', 'Salta', 'Rosario de la Frontera', 'Via Cargo'),
  ('via_cargo', 'Salta', 'Salta', 'Via Cargo'),
  ('via_cargo', 'Salta', 'Salvador Mazza', 'Via Cargo'),
  ('via_cargo', 'Salta', 'Tartagal', 'Via Cargo'),
  ('via_cargo', 'San Juan', 'Caucete', 'Via Cargo'),
  ('via_cargo', 'San Juan', 'San Juan', 'Via Cargo'),
  ('via_cargo', 'San Luis', 'Justo Daract', 'Via Cargo'),
  ('via_cargo', 'San Luis', 'La Punta', 'Via Cargo'),
  ('via_cargo', 'San Luis', 'Merlo San Luis', 'Via Cargo'),
  ('via_cargo', 'San Luis', 'San Luis', 'Via Cargo'),
  ('via_cargo', 'San Luis', 'Tilisarao', 'Via Cargo'),
  ('via_cargo', 'San Luis', 'Villa Mercedes', 'Via Cargo'),
  ('via_cargo', 'Santa Cruz', 'Caleta Olivia', 'Via Cargo'),
  ('via_cargo', 'Santa Cruz', 'El Calafate', 'Via Cargo'),
  ('via_cargo', 'Santa Cruz', 'Las Heras', 'Via Cargo'),
  ('via_cargo', 'Santa Cruz', 'Perito Moreno', 'Via Cargo'),
  ('via_cargo', 'Santa Cruz', 'Pico Truncado', 'Via Cargo'),
  ('via_cargo', 'Santa Cruz', 'Piedra Buena', 'Via Cargo'),
  ('via_cargo', 'Santa Cruz', 'Puerto San Julian', 'Via Cargo'),
  ('via_cargo', 'Santa Cruz', 'Rio Gallegos', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Cañada de Gomez', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Ceres', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Esperanza', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Firmat', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Gobernador Crespo', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Rafaela', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Reconquista', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Rosario', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Rosario Sur', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Rufino', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'San Justo (STF)', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'San Lorenzo', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Santa Fe', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Santo Tome (SFE)', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Sunchales', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Teodelina', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Totoras', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Venado Tuerto', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Vera', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Villa Cañas', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Villa Constitucion', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Villa Minetti', 'Via Cargo'),
  ('via_cargo', 'Santa Fe', 'Villa Ocampo', 'Via Cargo'),
  ('via_cargo', 'Santiago del Estero', 'Colonia Dora', 'Via Cargo'),
  ('via_cargo', 'Santiago del Estero', 'Fernandez', 'Via Cargo'),
  ('via_cargo', 'Santiago del Estero', 'Forres', 'Via Cargo'),
  ('via_cargo', 'Santiago del Estero', 'Frias', 'Via Cargo');

INSERT INTO public.transport_coverage (source, provincia, localidad, transporte) VALUES
  ('via_cargo', 'Santiago del Estero', 'La Banda', 'Via Cargo'),
  ('via_cargo', 'Santiago del Estero', 'Loreto', 'Via Cargo'),
  ('via_cargo', 'Santiago del Estero', 'Monte Quemado', 'Via Cargo'),
  ('via_cargo', 'Santiago del Estero', 'Santiago del Estero', 'Via Cargo'),
  ('via_cargo', 'Santiago del Estero', 'Termas de Rio Hondo', 'Via Cargo'),
  ('via_cargo', 'Santiago del Estero', 'Villa Ojo de Agua', 'Via Cargo'),
  ('via_cargo', 'Tucumán', 'Concepcion de Tucuman', 'Via Cargo'),
  ('via_cargo', 'Tucumán', 'Famailla', 'Via Cargo'),
  ('via_cargo', 'Tucumán', 'Juan Bautista Alberdi (tuc)', 'Via Cargo'),
  ('via_cargo', 'Tucumán', 'Monteros', 'Via Cargo'),
  ('via_cargo', 'Tucumán', 'San Miguel de Tucuman', 'Via Cargo'),
  ('via_cargo', 'Tucumán', 'Yerba Buena', 'Via Cargo'),
  ('snaider', 'Chaco', 'Antequeras', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Basail', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Charata', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Colonia Benitez', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Colonia Popular', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Coronel Du Graty', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Corzuela', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Fontana', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'General Pinedo', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Gral San Martin', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Hermoso Campo', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Juan Jose Castelli', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'La Leonesa', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Las Breñas', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Machagai', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Margarita Belen', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Pcia Roque Saenz Peña', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Pcia. de la Plaza', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Puerto Tirol', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Quitilipi', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Resistencia', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Sáenz Peña', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Samuhú', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Santa Sylvina', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Taco Pozo', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Villa Angela', 'Transporte Snaider'),
  ('snaider', 'Chaco', 'Villa Berthet', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'Bella Vista', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'Chavarría', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'Corrientes', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'Curuzú Cuatiá', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'Esquina', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'Goya', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'Ituzaingó', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'La Cruz', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'Libres', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'Mburucuyá', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'Mercedes', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'Mocoretá', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'Monte Caseros', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'Paso de la Patria', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'Paso de los Libres', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'Saladas', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'San Cosme', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'San Luis del Palmar', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'Santa Lucía', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'Santo Tomé', 'Transporte Snaider'),
  ('snaider', 'Corrientes', 'Tatacuá', 'Transporte Snaider'),
  ('snaider', 'Formosa', 'Clorinda', 'Transporte Snaider'),
  ('snaider', 'Formosa', 'El Colorado', 'Transporte Snaider'),
  ('snaider', 'Formosa', 'Formosa', 'Transporte Snaider'),
  ('snaider', 'Formosa', 'General Lucio Victorio Mansilla', 'Transporte Snaider'),
  ('snaider', 'Formosa', 'Herradura', 'Transporte Snaider'),
  ('snaider', 'Formosa', 'Pirané', 'Transporte Snaider'),
  ('snaider', 'Misiones', '2 de Mayo', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Aristóbulo del Valle', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Bernardo de Irigoyen', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Bonpland', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Campo Grande', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Candelaria', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Cerro Azul', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'El Soberbio', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Eldorado', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Garuhapé', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Garupá', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Jardín América', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Leandro N. Alem', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Montecarlo', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Oberá', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Posadas', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Puerto Esperanza', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Puerto Leoni', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Puerto Piray', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Puerto Rico', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'San Antonio', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'San Ignacio', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'San Martín', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'San Vicente', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Santa Ana', 'Transporte Snaider'),
  ('snaider', 'Misiones', 'Wanda', 'Transporte Snaider'),
  ('snaider', 'Santa Fe', 'Avellaneda (SF)', 'Transporte Snaider'),
  ('snaider', 'Santa Fe', 'Esperanza', 'Transporte Snaider'),
  ('snaider', 'Santa Fe', 'Gálvez', 'Transporte Snaider'),
  ('snaider', 'Santa Fe', 'Laguna Paiva', 'Transporte Snaider'),
  ('snaider', 'Santa Fe', 'Monte Vera', 'Transporte Snaider'),
  ('snaider', 'Santa Fe', 'Nelson', 'Transporte Snaider'),
  ('snaider', 'Santa Fe', 'Rafaela', 'Transporte Snaider'),
  ('snaider', 'Santa Fe', 'Reconquista', 'Transporte Snaider'),
  ('snaider', 'Santa Fe', 'Recreo', 'Transporte Snaider'),
  ('snaider', 'Santa Fe', 'San Carlos Centro', 'Transporte Snaider'),
  ('snaider', 'Santa Fe', 'Santa Fe', 'Transporte Snaider'),
  ('snaider', 'Santa Fe', 'Santo Tomé', 'Transporte Snaider'),
  ('mym', 'Corrientes', 'Corrientes', 'MyM');


DO $$
DECLARE
  v_count int;
BEGIN
  SELECT count(*) INTO v_count FROM public.transport_coverage;
  IF v_count <> 1005 THEN
    RAISE EXCEPTION 'transport_coverage: se esperaban 1005 filas, hay %', v_count;
  END IF;
END $$;
