import fs from 'fs';
import https from 'https';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const URL = 'https://raw.githubusercontent.com/wecodeio/ciudades-argentinas/master/ciudades-argentinas.json';
const OUTPUT_FILE = path.join(__dirname, '../admin/argentina-cities-data.js');

console.log(`Fetching cities from ${URL}...`);

https.get(URL, (res) => {
    let data = '';

    res.on('data', (chunk) => {
        data += chunk;
    });

    res.on('end', () => {
        try {
            const jsonData = JSON.parse(data);
            const provinceCities = {};

            jsonData.forEach(province => {
                // Some normalization might be needed
                let provinceName = province.nombre;

                // Map common names if needed (e.g., "Ciudad Autonoma De Bs As" -> "CABA")
                if (provinceName === "Ciudad Autonoma De Bs As") provinceName = "CABA";
                if (provinceName === "Tierra Del Fuego") provinceName = "Tierra del Fuego";
                if (provinceName === "Santiago Del Estero") provinceName = "Santiago del Estero";

                // Extract city names
                const cities = province.ciudades.map(c => c.nombre).sort();
                provinceCities[provinceName] = cities;
            });

            const fileContent = `// Generated by scripts/fetch-cities.js
// Data source: ${URL}
// Generated at: ${new Date().toISOString()}

export const PROVINCE_CITIES_DATA = ${JSON.stringify(provinceCities, null, 2)};
`;

            fs.writeFileSync(OUTPUT_FILE, fileContent);
            console.log(`Successfully wrote city data to ${OUTPUT_FILE}`);
            console.log(`Total provinces: ${Object.keys(provinceCities).length}`);

        } catch (error) {
            console.error('Error parsing JSON:', error);
        }
    });

}).on('error', (err) => {
    console.error('Error fetching data:', err);
});
